Feat: bchSuspended flag added to bws config
bitpay/bitcore pull request #3006
Opened 2020-11-11 19:52 UTC by Gamboster

2020-11-12 13:01 UTC, matiu requested changes

2020-11-12 18:16 UTC, Gamboster commented on packages/bitcore-wallet-service/src/config.ts
> +  bchSuspended: false,
much better 👍

2020-11-12 18:17 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/errors/errordefinitions.ts
> +  BCH_SUSPENDED: 'BCH network is upgrading. Please try later.',
done

2020-11-12 18:17 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/server.ts
> +          if (wallet.coin == 'bch' && config.bchSuspended == true) return cb(Errors.BCH_SUSPENDED);
done

2020-11-13 13:30 UTC, matiu approved these changes
Great job!

2020-11-13 13:30 UTC, merged