Improve Insight Search Performance
bitpay/bitcore pull request #3111
Opened 2021-03-04 05:47 UTC by unusualbob

Implements regex based smart searching to limit api calls to only valid paths based on what input is detected.
As txids and block ids are by far the most shared format, the current implementation of this code avoids querying eth if the 0x prefix is not present. If querying for eth without the 0x prefix is a common occurrence it can be included.

As we add more currencies and there is even more overlap of txids and block ids, it may make sense to ask the user which currency they're querying for when their query would hit more than 2 chains/networks.

Reviewer: Please double check I haven't missed any strange edge cases in regards to address/block/txid formats.

2021-03-04 19:01 UTC, matiu commented
Nice idea!

2021-03-05 13:01 UTC, nitsujlangston requested changes

2021-03-05 13:01 UTC, nitsujlangston commented on packages/insight/src/providers/search/search.ts
> +        { chain: 'DOGE', network: 'testnet' }
missing ETH block number

2021-03-05 20:45 UTC, unusualbob commented on packages/insight/src/providers/search/search.ts
> +        { chain: 'DOGE', network: 'testnet' }
Fixed

2021-03-05 22:35 UTC, nitsujlangston approved these changes

2021-03-05 22:35 UTC, merged