[FEAT] custom tokens push notifications
bitpay/bitcore pull request #3253
Opened 2021-08-28 02:06 UTC by gabrielbazan7

2021-09-09 16:13 UTC, rastajpa approved these changes
Nice work! 
![Screenshot_2021-09-09-13-10-40-094_com miui home](https://user-images.githubusercontent.com/10969512/132723037-1bbc4def-ba32-4aaa-b991-77f7253fb48e.jpg)

2021-09-22 17:55 UTC, cmgustavo submitted a review, later dismissed
ACK!

2021-09-30 20:55 UTC, kajoseph requested changes

2021-09-30 20:55 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/pushnotificationsservice.ts
> +              throw new Error('Notifications for unsupported token are not allowed');
Could you change this to be different than the error message below? It makes it harder to debug if the same error is thrown in multiple places.

2021-10-05 16:27 UTC, kajoseph approved these changes
LGTM

2021-10-05 18:00 UTC, merged