Fix unspent inputs
bitpay/bitcore pull request #3411
Opened 2022-08-15 17:53 UTC by escottalexander

This updates pending inputs of invalid transactions back to an unspent status.

2022-08-17 16:11 UTC, kajoseph requested changes
I think you're on the right track - thanks for doing this. Just some relatively minor things and a few best-practice items

2022-08-17 16:11 UTC, kajoseph commented on packages/bitcore-node/migrations/fixUnspentInputs.js
> +    async runScript() {
Let's add a param to do a dry-run that outputs the txids that will be changed. By default, it should do a dry-run and then have a cli param to run it for real

2022-08-17 16:11 UTC, kajoseph commented on packages/bitcore-node/migrations/fixUnspentInputs.js
> +/****************************************
Add a shebang to the top of the file `#!/usr/bin/env node` and give this file execution permissions `chmod +x fixUnspentInputs.js`

2022-08-18 21:08 UTC, kajoseph commented on packages/bitcore-node/migrations/fixUnspentInputs.js
> +                    const invalidTxs = await this.transactionModel.collection.find({ chain, network, blockHeight: -3 }).toArray();
Ah ok. Might be good to just make a local const then

2022-08-21 10:38 UTC, mohammadfarari1360 reviewed
Okay

2022-08-22 12:52 UTC, escottalexander commented
> I think you're on the right track - thanks for doing this. Just some relatively minor things and a few best-practice items

Thanks for your input. I made the revisions you suggested. Let me know if you see anything else.

2022-08-22 14:57 UTC, kajoseph approved these changes
Looks good

2022-08-22 14:59 UTC, merged

2022-08-23 05:52 UTC, mohammadfarari1360 reviewed
Okay good