Block Syncing enabled for Polygon in Bitcore-Node
bitpay/bitcore pull request #3442
Opened 2022-09-30 22:13 UTC by escottalexander

This makes it possible to do block syncing for Polygon. It also contains a new EVM base class that both ETH and MATIC are using. As such there are a lot of files changed but mostly just changes to class names.

2022-10-04 21:38 UTC, kajoseph requested changes

2022-10-06 17:32 UTC, escottalexander commented on packages/bitcore-node/src/providers/chain-state/evm/types.ts
> +export type Networks = 'mainnet' | 'mumbai';
My bad, think I accidentally used the MATIC types file. Corrected to include networks on both MATIC and ETH.

2022-10-06 17:33 UTC, escottalexander commented on packages/bitcore-node/src/providers/chain-state/evm/types.ts
> +export interface EventLog<T> {
I removed the csp definition and just made sure everything was included in types file.

2022-10-06 17:33 UTC, escottalexander commented on packages/bitcore-node/src/providers/chain-state/evm/models/transaction.ts
> +          const { web3 } = await CSP.getWeb3(network);
Good call. Moved outside the map function.

2022-10-06 17:34 UTC, escottalexander commented on packages/bitcore-node/src/modules/ethereum/api/csp.ts
> +export const ETH = new ETHStateProvider('ETH');
👍

2022-10-07 15:38 UTC, kajoseph approved these changes
LGTM. Tested

2022-10-07 15:38 UTC, merged