[Bitcore-Client] Adds a method for bumping fee for stuck TX
bitpay/bitcore pull request #3457
Opened 2022-10-14 20:13 UTC by escottalexander

This PR works for EVM based chains only. UTXO support will be added in another PR.

Tested against my local devnet and Goerli. Works with a raw tx or a tx id.

2022-11-10 15:07 UTC, kajoseph requested changes
A few minor things. I haven't tested it yet

2022-11-10 16:34 UTC, escottalexander commented on packages/bitcore-client/bin/wallet-bump-tx
> +  .option('--storageType [storageType]', 'optional - name of the database to use (default Level)')
I assume you mean storageType. I can change it but all the other utils have it like this. If I change it here, I should change them all.

2022-11-10 16:46 UTC, kajoseph requested changes
We should do a check and stop if the new gwei <= old gwei. If I don't specify --gwei at all, then it displays `Bumping gas price from 20 GWei to 20 GWei` and asks me if I want to broadcast, but it's easy to miss that message

2022-11-10 16:46 UTC, kajoseph commented on packages/bitcore-client/bin/wallet-bump-tx
> +      newFeeInWei = Number(gwei) * 1000000000;
I would suggest making 1000000000 a variable and using it everywhere we have `1000000000`. Things like this make it easy to miss a zero in one place or something

2022-11-10 17:47 UTC, kajoseph commented on packages/bitcore-client/bin/wallet-bump-tx
> +  .option('--storageType [storageType]', 'optional - name of the database to use (default Level)')
I was actually referring to the description. --path starts with "Custom wallet..." whereas --storageType starts with "name of...".

Also, we have REQUIRED in all upper case and optional in all lower case...which I suppose is fine but not having REQUIRED implies it's optional so we really don't need "optional" for the optional flags.

2022-11-10 17:52 UTC, kajoseph commented on packages/bitcore-client/bin/wallet-bump-tx
> +  .option('--storageType [storageType]', 'optional - name of the database to use (default Level)')
Also, --gwei starts with the default whereas --storageType ends with the default. I imagine you're mostly copying and pasting from other utils, but I'd like to increase our standard for attention to detail

2022-11-14 17:45 UTC, escottalexander commented
> We should do a check and stop if the new gwei <= old gwei. If I don't specify --gwei at all, then it displays Bumping gas price from 20 GWei to 20 GWei and asks me if I want to broadcast, but it's easy to miss that message

@kajoseph At one point I actually had the check you recommend but as I thought about it it seemed like it isn't necessary. If you provide --gwei then it checks to make sure it is more than the existing gwei. If you don't specify the gwei then it gets the current market rate which should always be greater than the tx's gwei granted it's truly stuck or else the original will go through momentarily and this util will error for using the same nonce. If you think it is still worthwhile for running against devnet then I can add it but I almost think it's more useful for testing against devnet to not handle this edge case.

2022-11-14 18:05 UTC, kajoseph commented
@escottalexander that seems sensible. We can leave it as is, then

2022-11-14 18:14 UTC, escottalexander commented
@kajoseph Thanks for the feedback. The requested changes have been committed.

2022-11-14 19:19 UTC, merged