Enable ETH and ETH ERC20 Payout Proposals
bitpay/bitcore pull request #3537
Opened 2023-02-08 22:05 UTC by leolambo

- Generates an ETH & ERC20 payout txp in BWS
- Adds the Multisend Contract ABI
- Provides the correct flags to create a raw ETH transaction to the multisend contract

**WAIT TO MERGE TILL AFTER MULTISEND CONTRACT IS FINALIZED.**

2023-02-10 20:22 UTC, kajoseph requested changes
There seems to be complexity with the gasLimit on the txp and the outputs. We should work to try and make the gasLimit be uniform. I don't think we need the gasLimit on the outputs if we're using the multisend contract.

2023-02-14 21:24 UTC, leolambo commented on packages/bitcore-wallet-service/src/lib/blockchainexplorers/v8.ts
> +    console.log('[v8.js.378:url:] CHECKING TOKEN ALLOWANCE', url);
it was used as the standard logger across most functions in V8.ts, changed to logger.info

2023-02-14 21:28 UTC, leolambo commented on packages/bitcore-wallet-service/src/lib/chain/eth/index.ts
> +            output.gasLimit = output.gasLimit ? output.gasLimit : Defaults.DEFAULT_MULTISEND_RECIPIENT_GAS_LIMIT;
defaultGasLimit has a large gas difference between erc20 and native wtih. The erc20 default gas limit being ~2.5x relative Multisend.sendErc20 's base needs

2023-02-15 22:39 UTC, kajoseph approved these changes

2023-02-15 22:41 UTC, merged