Ref: getServicesData from config
bitpay/bitcore pull request #3547
Opened 2023-03-01 22:18 UTC by Gamboster

Refactor for the `getServicesData` function that was not being used anymore

This will allow us to customize the config of the external services, for the different cases of logged in/logged out users, with different locations and versions of the app.
In this way we can perform certain blocks directly from BWS without the need of a new release of the bitpay app.

The first acceptance criteria for this is as follows:
Show error message “Changelly is currently unavailable in your area.” when “New Yorker” attempts to access SWAP functionality

Logged out and New York IP - RESTRICT
Logged in with New York Address - RESTRICT
Logged in with NON New York Address while in NY IP - ALLOW
Other cases - ALLOW

2023-03-14 02:16 UTC, kajoseph requested changes
It works :+1: , but could be cleaned up a bit

2023-03-14 02:16 UTC, kajoseph commented on packages/bitcore-wallet-service/test/integration/server.js
> +      it('should return swap crypto disabled if the user is logued out and located in NY', () => {
typo

2023-03-14 02:16 UTC, kajoseph commented on packages/bitcore-wallet-service/test/integration/server.js
> +      it('should return config.services with swap crypto disabled if it is included in the config file, the user is logued out and located in NY', () => {
typo

2023-03-14 02:16 UTC, kajoseph commented on packages/bitcore-wallet-service/test/integration/server.js
> +      it('should return config.services with swap crypto disabled if it is included in the config file and incomplete, the user is logued out and located in NY', () => {
typo

2023-03-15 15:43 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/model/external_services.ts
> +  disabledTitle?: string;
I added this option in case it was necessary. But if not specified, the app will put a title by default.

2023-03-15 15:50 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/server.ts
> +  getServicesData(opts, cb) {
Done!

2023-03-15 15:51 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/server.ts
> +            externalServicesConfig.swapCrypto = {...externalServicesConfig.swapCrypto, ...{ disabled: true, disabledMessage: 'Changelly is currently unavailable in your area.'}};
I changed it to 'Swaps are currently unavailable in your area.' I think it is more understandable for users

2023-03-15 15:52 UTC, Gamboster commented on packages/bitcore-wallet-service/test/integration/server.js
> +      it('should return swap crypto disabled if the user is logued out and located in NY', () => {
Fixed. Ty

2023-03-15 15:52 UTC, Gamboster commented on packages/bitcore-wallet-service/test/integration/server.js
> +      it('should return config.services with swap crypto disabled if it is included in the config file, the user is logued out and located in NY', () => {
Fixed. Ty

2023-03-15 16:07 UTC, merged