EVM nonce management
bitpay/bitcore pull request #3553
Opened 2023-03-08 21:39 UTC by leolambo

EVM nonce is set at transaction signing unless it was specified during transaction creation.
A transactions nonce is relative to the number of signed unbroadcasted transactions for the given wallet.

2023-03-13 16:42 UTC, kajoseph requested changes

2023-03-13 16:42 UTC, kajoseph commented on packages/bitcore-wallet-client/src/lib/common/utils.ts
> +            nonce: txp.nonce ? Number(txp.nonce) + Number(index): null,
This and above should be `txp.nonce != null ? ...` so that if txp.nonce == 0 it doesn't set it to null.

2023-03-13 16:42 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/chain/eth/index.ts
> +          nonce: txp.nonce ? Number(txp.nonce) + Number(index) : null,
This and above should be `txp.nonce != null ? ...` so that if txp.nonce == 0 it doesn't set it to null.

2023-03-13 16:42 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/chain/matic/index.ts
> +        nonce: txp.nonce ? Number(txp.nonce) + Number(index) : null,
txp.nonce != null

2023-03-13 16:42 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/server.ts
> +                  if (!opts.nonce && !ChainService.isEVMChain(wallet.chain)) {
opts.nonce != null

2023-03-13 16:42 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/server.ts
> +        if (!txp.nonce && ChainService.isEVMChain(wallet.chain)) {
txp.nonce != null

2023-03-24 20:38 UTC, leolambo commented
bitpay wallet changes that uses setNonce: https://github.com/leolambo/bitpay-app/pull/1/files

2023-05-31 21:50 UTC, kajoseph requested changes

2023-05-31 21:50 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/server.ts
> +      this.lock.releaseLock(lockName, err => {
this.lock.releaseLock is undefined

2024-01-04 15:13 UTC, closed without merging