[BCN] Add Type 2 fee's to api
bitpay/bitcore pull request #3664
Opened 2023-12-07 21:11 UTC by leolambo

Add type 2 fee support to BCN api.
Relies on this [crypto-rpc PR ](https://github.com/bitpay/crypto-rpc/pull/191) and a subsequent package update to support fetching priority fee.

2023-12-28 22:16 UTC, kajoseph requested changes
I would recommend adding a separate endpoint for priority fee estimation in `eth-routes.ts` and `matic-routes.ts`. That would clean up a lot of the branching logic for the EVM fee nuances. Since EVM now has 3 permutations for fee estimation, it gets somewhat messy trying to keep them all the same but separate. We can have the type0 gasPrice and type2 base fee use the same path, and separate priority fee.

Also, this seems to overlap with https://github.com/bitpay/bitcore/pull/3660. How do these reconcile?

2023-12-29 17:35 UTC, leolambo commented on packages/bitcore-node/src/providers/chain-state/evm/api/csp.ts
> +      txType = txType || 2;
yes, priorityFee is not type 0 compatible

2023-12-29 17:37 UTC, leolambo commented on packages/bitcore-node/test/integration/ethereum/csp.spec.ts
> +/*  it('should be able to get type 2 fees', async () => {
relied on this pr https://github.com/bitpay/crypto-rpc/pull/191. crypto rpc now needs to be updated

2023-12-29 19:25 UTC, kajoseph requested changes

2023-12-29 19:25 UTC, kajoseph commented on packages/bitcore-node/src/modules/matic/api/matic-routes.ts
> +MaticRoutes.get('/api/ETH/:network/priorityFee/:percentile', async (req, res) => {
MATIC

2024-01-11 20:41 UTC, kajoseph requested changes

2024-01-11 20:41 UTC, kajoseph commented on packages/bitcore-node/src/providers/chain-state/evm/api/csp.ts
> +    let { network, target = 4, txType, priorityFeePercentile } = params;
We should decouple the priority fee from this method altogether and make another method called like `getPriorityFee`. I don't think we need one mega function that handles all the things...having separate functions that are called in their own contexts would be ideal, I think

2024-01-16 15:48 UTC, kajoseph approved these changes
tACK

2024-01-16 15:49 UTC, merged