[BCC] Handle uncontrolled change
bitpay/bitcore pull request #3674
Opened 2024-01-04 17:35 UTC by kajoseph

This handles the case when the tx is a sweep/max send and all given utxos should be used.

2024-01-04 21:19 UTC, escottalexander requested changes
Everything is good here and works. Just remove the Web3 ref at the top of wallet-bump-tx.

2024-01-04 21:19 UTC, escottalexander commented on packages/bitcore-client/bin/wallet-bump-tx
You can remove the reference to Web3 on line 8.

2024-01-04 21:21 UTC, escottalexander approved these changes
LGTM!

2024-01-05 15:45 UTC, nitsujlangston approved these changes

2024-01-05 15:46 UTC, merged