[Libs] Add tx size & vsize, use it for accurate fee calculation
bitpay/bitcore pull request #3686
Opened 2024-01-23 15:47 UTC by kajoseph

This adds `size` and `vsize` properties to the Transaction prototype (except for the BCH lib, it only gets the `size` property). The size/vsize is then used in fee calculations to produce a more accurate fee (which is a lot less for segwit txs). The previously used `_estimateSize()` produced a very rough size estimation that was "fine" for a low fee market, but in this high fee market the size and fee calculations matter.

In addition to being more accurate, using the size/vsize was ~2x faster than using `_estimateSize()`.

2024-01-24 20:15 UTC, escottalexander requested changes
To sum up our conversation in Slack: vsize is calcuated without the signature which leads to an underestimation.

2024-01-31 17:52 UTC, escottalexander requested changes
A few questions/recommendations to look at. Otherwise seems to work as expected.

2024-01-31 18:30 UTC, escottalexander approved these changes
LGTM!

2024-03-02 02:31 UTC, nitsujlangston approved these changes

2024-03-05 20:12 UTC, merged