[Multi] Regtest support
bitpay/bitcore pull request #3696
Opened 2024-02-14 16:30 UTC by kajoseph

This adds natural regtest support in a way that doesn't require you to clobber testnet. This is necessary because several currencies have address formats that are different between regtest and testnet.

2024-02-20 19:59 UTC, escottalexander requested changes
Just a few things to look over.

2024-02-21 15:14 UTC, kajoseph commented on packages/bitcore-wallet-service/src/lib/chain/btc/index.ts
> +    if (addrNetwork === 'testnet' && walNetwork === 'regtest') {
Yes, this is intentional. I believe `addrNetwork` was set to `regtest` before if `regtestEnabled` was true in the config. This new way allows testnet and regtest to coexist but addresses that are valid for both testnet and regtest will default to a `testnet` network.

I'm going to look at this again, though. The util fn I made to compare networks might able to be applied here.

2024-03-06 14:26 UTC, escottalexander approved these changes
LGTM!

2024-03-06 14:57 UTC, nitsujlangston approved these changes

2024-03-06 14:58 UTC, merged