feat: Sardine
bitpay/bitcore pull request #3781
Opened 2024-07-31 14:04 UTC by mahume

- add methods and API endpoints for fetching supported tokens from Sardine
- add tests for new function

2024-07-31 15:01 UTC, Gamboster requested changes

2024-07-31 15:01 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/expressapp.ts
> +      getServerWithAuth(req, res, server => {
I would not use getServerWithAuth to fetch supported tokens/currencies. You can do it directly like this example:

router.post('/v1/service/ramp/assets', async (req, res) => {
      let server, response;
      try {
        server = getServer(req, res);
        response = await server.rampGetAssets(req);
        return res.json(response);
      } catch (err) {
        return returnError(err ?? 'unknown', res, req);
      }
    });

2024-07-31 15:01 UTC, Gamboster commented on packages/bitcore-wallet-client/src/lib/api.ts
> +  sardineGetSupportedTokens(data): Promise<any> {
A BWC bump will not be necessary. By not using getServerWithAuth we can access through our BWS URL directly (.../v1/service/sardine/getSupportedTokens). So you can remove this function.

2024-07-31 15:01 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/server.ts
> +      this.request.post(
we should use this.request.get(...

2024-07-31 15:01 UTC, Gamboster commented on packages/bitcore-wallet-service/src/lib/server.ts
> +          body: req.body,
This method does not requiere body parameters
https://docs.sardine.ai/docs/integrate-payments/on-ramp-api/operations/list-supported-tokens

2024-07-31 15:31 UTC, mahume commented
Changes pushed. Please test locally as I am coding this blind without Bitcore running locally.

2024-08-02 14:28 UTC, Gamboster approved these changes
LGTM

2024-08-05 15:05 UTC, kajoseph approved these changes

2024-08-05 15:06 UTC, merged